/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * DevStage.API
 * OpenAPI spec version: 1.0
 */
import { customFetcher } from '../../orval-fetcher';
export interface RequestRegisterSubscriptionJson {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  referredId?: string | null;
}

export interface ResponseErrorJson {
  /** @nullable */
  errorMessages?: string[] | null;
  /** @nullable */
  method?: string | null;
}

export interface ResponseRank {
  /** @nullable */
  ranking?: ResponseSubscriberRankingPositionJson[] | null;
}

export interface ResponseRegisterSubscriptionJson {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  referredId?: string | null;
}

export interface ResponseSubscriberRankingPositionJson {
  subscriberId?: string;
  /** @nullable */
  name?: string | null;
  position?: number;
  score?: number;
}

export interface ResponseSubscriberTotalInvitesJson {
  totalInvites?: number;
}

export interface ResponseSubscriberTotalSubscriptions {
  totalSubscriptions?: number;
}



/**
 * Access invite link and redirects user to the event
 */
export const getGetSubscriberIdInviteUrl = (subscriberId: string,) => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/${subscriberId}/invite`
}

export const getSubscriberIdInvite = async (subscriberId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetcher<unknown>(getGetSubscriberIdInviteUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get total invites clicks for the subscriber
 */
export const getGetSubscriberIdTotalinvitesclicksUrl = (subscriberId: string,) => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/${subscriberId}/totalinvitesclicks`
}

export const getSubscriberIdTotalinvitesclicks = async (subscriberId: string, options?: RequestInit): Promise<ResponseSubscriberTotalInvitesJson> => {
  
  return customFetcher<ResponseSubscriberTotalInvitesJson>(getGetSubscriberIdTotalinvitesclicksUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Subscribes to the event
 */
export const getPostSubscriptionsUrl = () => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/subscriptions`
}

export const postSubscriptions = async (requestRegisterSubscriptionJson: RequestRegisterSubscriptionJson, options?: RequestInit): Promise<ResponseRegisterSubscriptionJson> => {
  
  return customFetcher<ResponseRegisterSubscriptionJson>(getPostSubscriptionsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestRegisterSubscriptionJson,)
  }
);}



/**
 * Get total converted invites into subscription for the subscriber
 */
export const getGetSubscriberIdTotalsubscriptionsUrl = (subscriberId: string,) => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/${subscriberId}/totalsubscriptions`
}

export const getSubscriberIdTotalsubscriptions = async (subscriberId: string, options?: RequestInit): Promise<ResponseSubscriberTotalSubscriptions> => {
  
  return customFetcher<ResponseSubscriberTotalSubscriptions>(getGetSubscriberIdTotalsubscriptionsUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get total converted invites into subscription for the subscriber
 */
export const getGetSubscriberIdGetrankingpositionUrl = (subscriberId: string,) => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/${subscriberId}/getrankingposition`
}

export const getSubscriberIdGetrankingposition = async (subscriberId: string, options?: RequestInit): Promise<ResponseSubscriberRankingPositionJson> => {
  
  return customFetcher<ResponseSubscriberRankingPositionJson>(getGetSubscriberIdGetrankingpositionUrl(subscriberId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get the total rank of the subscribers
 */
export const getGetGetrankUrl = () => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/getrank`
}

export const getGetrank = async ( options?: RequestInit): Promise<ResponseRank> => {
  
  return customFetcher<ResponseRank>(getGetGetrankUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get top three rank of the subscribers
 */
export const getGetGettopthreerankUrl = () => {


  return `https://yyipe2h53h.us-east-1.awsapprunner.com/gettopthreerank`
}

export const getGettopthreerank = async ( options?: RequestInit): Promise<ResponseRank> => {
  
  return customFetcher<ResponseRank>(getGetGettopthreerankUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



